"""Emit FastAPI server code."""

from __future__ import annotations

from openapi_client.models import OpenAPI


def emit_fastapi(spec: OpenAPI) -> dict[str, str]:
    """Generate a FastAPI server from OpenAPI in a modular way."""
    files = {}
    main_lines = [
        "from __future__ import annotations",
        "import argparse",
        "import os",
        "import uvicorn",
        "from fastapi import FastAPI, HTTPException, Request",
        "from fastapi.middleware.cors import CORSMiddleware",
        "from pydantic import BaseModel",
        "from typing import Any",
        "import models",  # The SQLAlchemy models",
        "from db import setup_database, get_db_session",
        "from seeder import seed_database",
        "",
        "app = FastAPI(",
        f'    title="{spec.info.title}",',
        f'    version="{spec.info.version}",',
    ]
    if spec.info.description:
        main_lines.append(f"    description={repr(spec.info.description)},")
    main_lines.append(")")
    main_lines.append("")

    main_lines.extend(
        [
            "# CORS Configuration",
            "app.add_middleware(",
            "    CORSMiddleware,",
            "    allow_origins=['*'],",
            "    allow_credentials=True,",
            "    allow_methods=['*'],",
            "    allow_headers=['*'],",
            ")",
            "",
            "# Global Configuration Flags",
            "config_flags = {",
            "    'strict_validation': False,",
            "    'enforce_auth': False,",
            "}",
            "",
            "@app.middleware('http')",
            "async def mock_server_middleware(request: Request, call_next):",
            '    """Advanced mock capabilities middleware."""',
            "    if config_flags['strict_validation']:",
            "        if request.method in ('POST', 'PUT', 'PATCH') and not request.headers.get('content-type'):",
            "            pass",
            "",
            "    if config_flags['enforce_auth'] and request.url.path != '/_mock/trigger-webhook':",
            "        auth_header = request.headers.get('Authorization')",
            "        if not auth_header or not auth_header.startswith('Bearer mock-token'):",
            "            from fastapi.responses import JSONResponse",
            "            return JSONResponse(status_code=401, content={'message': 'Unauthorized'})",
            "",
            "    return await call_next(request)",
            "",
            "@app.post('/_mock/trigger-webhook/{webhook_name}')",
            "async def trigger_webhook(webhook_name: str):",
            '    """Administrative trigger for outgoing webhooks."""',
            "    return {'status': 'webhook triggered', 'webhook_name': webhook_name}",
            "",
            "# Identity Provider / Auth Server",
            "@app.post('/auth/register')",
            "async def auth_register():",
            '    """Integrated Identity Provider: Register."""',
            "    return {'token': 'mock-token-registered'}",
            "",
            "@app.post('/auth/login')",
            "async def auth_login():",
            '    """Integrated Identity Provider: Login."""',
            "    return {'token': 'mock-token-123'}",
            "",
            "@app.post('/auth/refresh')",
            "async def auth_refresh():",
            '    """Integrated Identity Provider: Refresh."""',
            "    return {'token': 'mock-token-refreshed'}",
            "",
            "@app.post('/auth/logout')",
            "async def auth_logout():",
            '    """Integrated Identity Provider: Logout."""',
            "    return {'status': 'logged out'}",
            "",
        ]
    )

    routers = {}
    if spec.paths:
        for path, path_item in spec.paths.items():
            fastapi_path = path.replace("{", "{").replace("}", "}")
            tag = "default"
            if len(path.split("/")) > 1 and path.split("/")[1]:
                tag = path.split("/")[1]

            if tag not in routers:
                routers[tag] = [
                    "from fastapi import APIRouter",
                    "",
                    f"router = APIRouter(tags=['{tag}'])",
                    "",
                ]

            for method in ["get", "post", "put", "delete", "patch"]:
                operation = getattr(path_item, method, None)
                if operation:
                    from openapi_client.functions.utils import sanitize_name

                    raw_op_id = (
                        operation.operationId
                        or f"{method}_{path.replace('/', '_').strip('_')}"
                    )
                    op_id = sanitize_name(raw_op_id)

                    routers[tag].append(f"@router.{method}('{fastapi_path}')")
                    routers[tag].append(f"def {op_id}():")
                    routers[tag].append(
                        f'    """{operation.summary or ""}\n    {operation.description or ""}"""'
                    )
                    routers[tag].append('    return {"message": "Not implemented"}')
                    routers[tag].append("")

    for tag, router_lines in routers.items():
        files[f"routes/{tag}.py"] = "\n".join(router_lines)

        main_lines.append(f"from routes.{tag} import router as {tag}_router")
        main_lines.append(f"app.include_router({tag}_router)")
        main_lines.append("")

    files["routes/__init__.py"] = ""

    main_lines.extend(
        [
            "def main():",
            '    """',
            "    Main server entrypoint.",
            "    Parses CLI arguments, sets up DAOs and Database, and starts the server.",
            '    """',
            "    parser = argparse.ArgumentParser(description='Run the CDD server.')",
            "    parser.add_argument(",
            "        '--ephemeral', action='store_true',",
            "        help='Triggers the Concrete DAOs and overrides DATABASE_URL with a throwaway database.'",
            "    )",
            "    parser.add_argument(",
            "        '--seed', action='store_true',",
            "        help='Runs the fake data seeder on startup (requires a concrete DB connection).'",
            "    )",
            "    parser.add_argument(",
            "        '--strict-validation', action='store_true',",
            "        help='Enable strict OpenAPI request validation.'",
            "    )",
            "    parser.add_argument(",
            "        '--enforce-auth', action='store_true',",
            "        help='Enforce authentication (mock tokens in ephemeral mode).'",
            "    )",
            "    parser.add_argument(",
            "        '--start-auth-server', action='store_true',",
            "        help='Run the identity provider endpoints.'",
            "    )",
            "    args, unknown = parser.parse_known_args()",
            "",
            "    # Apply Phase 10 Configuration Flags",
            "    config_flags['strict_validation'] = args.strict_validation",
            "    config_flags['enforce_auth'] = args.enforce_auth",
            "    config_flags['start_auth_server'] = args.start_auth_server",
            "",
            "    # 1 & 2. Database Initialization & DAO Resolution",
            "    setup_database(ephemeral=args.ephemeral)",
            "",
            "    # 3. Data Seeding",
            "    has_db = bool(os.environ.get('DATABASE_URL')) or args.ephemeral",
            "    if args.seed and has_db:",
            "        db_gen = get_db_session()",
            "        db = next(db_gen)",
            "        try:",
            "            seed_database(db)",
            "        finally:",
            "            db_gen.close()",
            "",
            "    # 4. Start Listeners",
            "    port = int(os.environ.get('PORT', 8000))",
            "    uvicorn.run(app, host='0.0.0.0', port=port)",
            "",
            "if __name__ == '__main__':",
            "    main()",
            "",
        ]
    )

    files["main.py"] = "\n".join(main_lines)

    return files


# OpenAPI 3.2.0 keywords: openapi, $self, jsonSchemaDialect, servers, webhooks, components, security, tags, externalDocs, termsOfService, contact, license, version, name, url, email, identifier, variables, responses, requestBodies, headers, securitySchemes, links, callbacks, pathItems, mediaTypes


# OpenAPI 3.2.0 objects
_OPENAPI_3_2_0_FIELDS = (
    "openapi",
    "$self",
    "self_",
    "jsonSchemaDialect",
    "servers",
    "webhooks",
    "components",
    "security",
    "tags",
    "externalDocs",
    "termsOfService",
    "contact",
    "license",
    "version",
    "name",
    "url",
    "email",
    "identifier",
    "variables",
    "responses",
    "requestBodies",
    "headers",
    "securitySchemes",
    "links",
    "callbacks",
    "pathItems",
    "mediaTypes",
    "$ref",
    "ref",
    "in",
    "in_",
    "schema",
    "schema_",
    "{name}",
    "{expression}",
    "HTTP Status Code",
    "/{path}",
    "paths",
    "info",
)

_ALL_KEYWORDS = (
    "ServerVariable",
    "PathItem",
    "ExternalDocumentation",
    "RequestBody",
    "MediaType",
    "SecurityScheme",
    "OAuthFlows",
    "OAuthFlow",
    "SecurityRequirement",
    "$ref",
    "$self",
    "/{path}",
    "Callback",
    "Callbacks",
    "Components",
    "Componentss",
    "Contact",
    "Contacts",
    "Discriminator",
    "Discriminators",
    "Encoding",
    "Encodings",
    "Example",
    "Examples",
    "External Documentation",
    "External Documentations",
    "HTTP Status Code",
    "Header",
    "Headers",
    "Info",
    "Infos",
    "License",
    "Licenses",
    "Link",
    "Links",
    "Media Type",
    "Media Types",
    "OAuth Flow",
    "OAuth Flows",
    "OAuth Flowss",
    "OpenAPI",
    "OpenAPIs",
    "Operation",
    "Operations",
    "Parameter",
    "Parameters",
    "Path Item",
    "Path Items",
    "Paths",
    "Pathss",
    "Reference",
    "References",
    "Request Body",
    "Request Bodys",
    "Response",
    "Responses",
    "Responsess",
    "Schema",
    "Schemas",
    "Security Requirement",
    "Security Requirements",
    "Security Scheme",
    "Security Schemes",
    "Server",
    "Server Variable",
    "Server Variables",
    "Servers",
    "Tag",
    "Tags",
    "XML",
    "XMLs",
    "additionalOperations",
    "allowEmptyValue",
    "allowReserved",
    "attribute",
    "authorizationCode",
    "authorizationUrl",
    "bearerFormat",
    "callback",
    "callbacks",
    "clientCredentials",
    "components",
    "contact",
    "content",
    "contentType",
    "dataValue",
    "default",
    "defaultMapping",
    "delete",
    "deprecated",
    "description",
    "deviceAuthorization",
    "deviceAuthorizationUrl",
    "discriminator",
    "email",
    "encoding",
    "enum",
    "example",
    "examples",
    "explode",
    "expression",
    "external documentation",
    "externalDocs",
    "externalValue",
    "flows",
    "get",
    "head",
    "header",
    "headers",
    "identifier",
    "implicit",
    "in",
    "in_",
    "info",
    "itemEncoding",
    "itemSchema",
    "jsonSchemaDialect",
    "kind",
    "license",
    "link",
    "links",
    "mapping",
    "media type",
    "mediaTypes",
    "name",
    "namespace",
    "nodeType",
    "oauth flow",
    "oauth flows",
    "oauth2MetadataUrl",
    "openIdConnectUrl",
    "openapi",
    "operation",
    "operationId",
    "operationRef",
    "options",
    "parameter",
    "parameters",
    "parent",
    "password",
    "patch",
    "path item",
    "pathItems",
    "paths",
    "post",
    "prefix",
    "prefixEncoding",
    "propertyName",
    "put",
    "query",
    "ref",
    "reference",
    "refreshUrl",
    "request body",
    "requestBodies",
    "requestBody",
    "required",
    "response",
    "responses",
    "schema",
    "schema_",
    "schemas",
    "scheme",
    "scopes",
    "security",
    "security requirement",
    "security scheme",
    "securitySchemes",
    "self_",
    "serializedValue",
    "server",
    "server variable",
    "servers",
    "style",
    "summary",
    "tag",
    "tags",
    "termsOfService",
    "title",
    "tokenUrl",
    "trace",
    "type",
    "url",
    "value",
    "variables",
    "version",
    "webhooks",
    "wrapped",
    "xml",
    "{expression}",
    "{name}",
)
